### ISSUE TITLE
Error while setup "name 'basestring' is not defined"

### ISSUE THREAD

**Issue by harshadag** [pratz/set-me-up#1]
~/set-me-up$ ansible-playbook -i inventory set_me_up.yml
ERROR! Unexpected Exception: name 'basestring' is not defined
to see the full traceback, use -vvv

Details:
~/set-me-up$ ansible-playbook -i inventory set_me_up.yml -vvv
No config file found; using defaults
ERROR! Unexpected Exception: name 'basestring' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/google/home/ghodke/anaconda3/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/google/home/ghodke/anaconda3/lib/python3.6/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/local/google/home/ghodke/anaconda3/lib/python3.6/site-packages/ansible/executor/playbook_executor.py", line 72, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/local/google/home/ghodke/anaconda3/lib/python3.6/site-packages/ansible/playbook/__init__.py", line 53, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/local/google/home/ghodke/anaconda3/lib/python3.6/site-packages/ansible/playbook/__init__.py", line 93, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/usr/local/google/home/ghodke/anaconda3/lib/python3.6/site-packages/ansible/playbook/play.py", line 115, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/local/google/home/ghodke/anaconda3/lib/python3.6/site-packages/ansible/playbook/base.py", line 206, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/usr/local/google/home/ghodke/anaconda3/lib/python3.6/site-packages/ansible/playbook/taggable.py", line 40, in _load_tags
    elif isinstance(ds, basestring):
NameError: name 'basestring' is not defined

May be issue with python version?

**Comment by pr4th4m** [comment]
Yap, ansbile does not completely support python 3.x yet
https://github.com/ansible/ansible/issues/14841
